import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>CookIT | Discover a new recipe to satisfy your taste</title>
      </Head>

      <main className='p-5'>
        <h1>CookIT</h1>
        <p>Discover a new recipe to satisfy your taste</p>
      </main>
    </div>
  )
}
