import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div className='font-new'>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>CookIT | Discover a new recipe to satisfy your taste</title>
      </Head>

      <main className="p-5 w-screen h-screen landing-img flex">
        <div className="md:w-[400px]"></div>
        <div className="flex-grow h-full w-full">
          <nav className="w-full flex justify-end items-center gap-6 px-4">
            <Link href="/sign-in">
              <a className="text-sm font-bold cursor-pointer text-gray-800 hover:text-gray-700">
                Sign In
              </a>
            </Link>
            <Link href="/sign-up">
              <a className="text-sm font-bold cursor-pointer text-gray-800 hover:text-gray-700">
                Sign Up
              </a>
            </Link>
          </nav>
          <header className="mt-64 md:mt-40 flex flex-col items-center">
            <h1 className="text-gray-800 text-4xl md:text-6xl my-2 font-new">
              CookIT
            </h1>
            <p className="text-gray-600 text-sm md:text-base mb-2">
              Discover a new recipe to satisfy your taste
            </p>
          </header>

          <form className="w-full flex flex-col items-center px-6">
            <div className="w-full sm:w-96 md:w-[500px] px-3 py-2 bg-white rounded-lg shadow-lg hover:shadow-none border-2 border-gray-200 my-3">
              <input
                type="text"
                className="w-full py-2 focus:outline-none text-sm"
                placeholder="Search for a recipe..."
              />
            </div>
            <button
              type="submit"
              className="w-full sm:w-96 md:w-[500px] px-3 py-2 text-gray-100 bg-gray-700 rounded-lg shadow-lg hover:shadow-none"
            >
              Search
            </button>
          </form>
        </div>
      </main>
    </div>
  );
}
