import React, { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import {
  ChevronLeft,
  ChevronRight,
  Lock,
  Mail,
  Person,
  Visibility,
  VisibilityOff,
} from '@mui/icons-material';

const SignUp = () => {
  const [ formData, setFormData ] = useState({
    name: '',
    email: '',
    password: '',
  })

  const { name, email, password } = formData
  const [visible, setVisible] = useState(false);

  const onChange = (e) => {
    setFormData((prevState) => ({
      ...prevState,
      [e.target.id] : e.target.value
    }))
  }

  const showPassword = () => {
    setVisible(!visible);
  };
  return (
    <div className="landing-img h-screen w-screen font-new">
      <Head>
        <meta
          name="description"
          content="A recipe app called CookIT Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
        <title>Create an Account | Sign up to CookIT</title>
      </Head>
      <div className="flex p-5 text-gray-800">
        <div className="md:w-[400px]"></div>
        <div className="w-full md:ml-40 flex-grow">
          <header className="p-3">
            <h2 className="font-extrabold text-3xl">Create an account</h2>
          </header>

          <main className="mt-3 p-2">
            <form>
            <div className="w-full flex gap-2 px-2 items-center md:w-[500px] bg-white rounded-lg shadow-lg hover:shadow-none border-2 border-gray-200 mb-6">
                <Person fontSize="small" />
                <input
                  type="text"
                  className="flex-grow focus:outline-none text-sm border-none py-2"
                  placeholder="Enter your full name..."
                  id='name'
                  value={name}
                  onChange={onChange}
                  required
                />
              </div>

              <div className="w-full flex gap-2 px-2 items-center md:w-[500px] bg-white rounded-lg shadow-lg hover:shadow-none border-2 border-gray-200 mb-6">
                <Mail fontSize="small" />
                <input
                  type="email"
                  className="flex-grow focus:outline-none text-sm border-none py-2"
                  placeholder="Enter a valid email..."
                  id='email'
                  value={email}
                  onChange={onChange}
                  required
                />
              </div>

              <div className="w-full flex gap-2 px-2 items-center md:w-[500px] bg-white rounded-lg shadow-lg hover:shadow-none border-2 border-gray-200 mb-3">
                <Lock fontSize="small" />
                <input
                  type={`${visible ? 'text' : 'password'}`}
                  className="flex-grow focus:outline-none text-sm border-none py-2"
                  placeholder="Enter your password..."
                  id='password'
                  value={password}
                  onChange={onChange}
                  required
                />

                {visible ? (
                  <Visibility fontSize="small" onClick={showPassword} />
                ) : (
                  <VisibilityOff fontSize="small" onClick={showPassword} />
                )}
              </div>

              <div className="flex justify-between items-center w-full md:w-[500px] mt-9">
                <h3 className="text-2xl font-black">Sign up</h3>
                <button
                  type="submit"
                  className="p-2 rounded-full bg-red-500 border-none shadow-lg hover:shadow-none"
                >
                  <ChevronRight className="text-white" />
                </button>
              </div>
            </form>

            {/* google oauth */}

            <div className="flex items-center gap-2 w-full md:w-[500px] mt-9">
              <Link
                href="/"
              >
                <a className="bg-red-500 p-1 rounded-full shadow-lg hover:shadow-none">
                  <ChevronLeft className="text-white" />
                </a>
              </Link>
              <p className="text-red-500 text-sm font-bold">Back home</p>
            </div>

            <div className="flex justify-center items-center w-full md:w-[500px] mt-9">
              <Link href="/sign-in" className="mb-3">
                <a className="text-red-500 font-bold">Sign in instead</a>
              </Link>
            </div>
          </main>
        </div>
      </div>
    </div>
  );
};

export default SignUp;
